name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.0'
      - run: rm -rf ./* && git checkout . 
      - run: flutter create . --overwrite --org com.ethiorate.app
      - run: rm lib/main.dart
      - run: flutter pub add google_mobile_ads http
      - name: Restore main.dart
        run: git checkout lib/main.dart
      - name: Restore AndroidManifest
        run: git checkout android/app/src/main/AndroidManifest.xml
      - run: flutter build apk --release
      - uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
